ARG NODE_VERSION

FROM node:${NODE_VERSION} AS build

COPY . /squad

WORKDIR /squad
RUN yarn cache clean --force
RUN rm -rf node_modules
RUN yarn install

FROM node:${NODE_VERSION}
WORKDIR /squad
COPY --from=build /squad /squad

ENTRYPOINT ["yarn", "run", "dev"]